name: 'Kiriban Action'
description: 'This action checks if the number is kiriban.'
author: 'kumackey <kumak1t09e0@gmail.com>'
runs:
  using: 'composite'
  steps:
    - id: check_kiriban
      run: |
        result=$(go run cmd/main.go ${{ github.event.number }})
        echo "is_kiriban=$result" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ github.action_path }}
    - uses: actions/github-script@v6
      shell: bash
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: `Congratulations! #${context.payload.pull_request.number} is kiriban! 🎉`
          }
          await github.rest.issues.createComment(params)
      if: steps.check_kiriban.outputs.is_kiriban == 'true'
branding:
  icon: 'gift'
  color: 'orange'