name: 'Kiriban Action'
description: 'This action checks if the number is kiriban.'
author: 'kumackey <kumak1t09e0@gmail.com>'
runs:
  using: "composite"
  steps:
    - run: go run main.go ${{ github.event.pull_request.number }}
      shell: bash
      working-directory: cmd
branding:
  icon: 'gift'
  color: 'orange'