name: 'Kiriban Action'
description: 'キリ番を判定するGithub Actions'
author: 'kumackey <kumak1t09e0@gmail.com>'
runs:
  using: 'composite'
  steps:
    - run: go run cmd/main.go ${{ github.event.number }}
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
branding:
  icon: 'gift'
  color: 'orange'
