name: 'Kiriban Action'
description: 'This action checks if the number is kiriban.'
author: 'kumackey <kumak1t09e0@gmail.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.event.number }}
branding:
  icon: 'gift'
  color: 'orange'