name: 'Kiriban Action'
description: 'This action checks if the number is kiriban.'
author: 'kumackey <kumak1t09e0@gmail.com>'
runs:
  using: 'composite'
  steps:
    - id: check_kiriban
      run: echo "is_kiriban=$(go run cmd/main.go ${{ github.event.number }})" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ github.workspace }}
    - run: gh issue comment ${{ github.event.number }} "Congratulations, this is kiriban!🎉"
      shell: bash
      if: steps.check_kiriban.outputs.is_kiriban == 'true'
branding:
  icon: 'gift'
  color: 'orange'