name: kiriban

on:
  pull_request:
    types: [ opened ]

jobs:
  kiriban:
    runs-on: ubuntu-latest
    steps:
      - uses: kumackey/kiriban@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
